### ISSUE TITLE
The include statement of snort.rules is added to snort.conf many times after each reboot.

### ISSUE THREAD

**Issue by hitohiros** [Mata-Elang-Stable/SnorqttAlpine-Sensor#2]
The include statement of snort.rules is added to snort.conf many times after each reboot.

/etc/snort/snort.conf
---
```
# site specific rules
include /etc/snort/rules/local.rules
include /etc/snort/rules/snort.rules
include /etc/snort/rules/snort.rules     <- unnecessary
include /etc/snort/rules/snort.rules     <- unnecessary
include /etc/snort/rules/snort.rules     <- unnecessary
```

**Comment by fadhilyori** [comment]
Okay. Thank you @hitohiros.
Let me check this. Maybe there is a bug in the startup script.

**Comment by fadhilyori** [comment]
https://github.com/Mata-Elang-Stable/SnorqttAlpine-Sensor/blob/f86b435f7a382b61150072fefc7b762b517dc85f/require/startup.sh#L14

**Comment by fadhilyori** [comment]
Hi @hitohiros , 

I have already fixed this issue. The changes already in dev branch
